### ISSUE TITLE
TypeError: show() got an unexpected keyword argument 'offscreen'

### ISSUE THREAD

**Issue by SeanNobel** [brainglobe/brainrender#160]
Hi, I wanted to try brainrender-gui, so I installed brainrender to my local anaconda environment.
I ran "brainrender-gui" and got some errors related to PySide and Qt, but fixed them somehow.
After that I ran brainrender-gui again, and got the error of the title.
I have no idea what's happening, I appreciate any help.

My versions are:
python 3.7.7
brainrender 2.0.2.9
vedo 2021.0.3

MacOS 10.15.7

When I run brainrender-gui, the GUI launches for 5 seconds or so, but shuts down and gives me that error.

![image](https://user-images.githubusercontent.com/75618251/118462172-5d397e80-b739-11eb-8256-3914c7241f06.png)
![image](https://user-images.githubusercontent.com/75618251/118462215-662a5000-b739-11eb-9070-9d31ca18a7d2.png)

**Comment by FedeClaudi** [comment]
Hey, 

This was introduced by a recent update in `vedo` (see https://github.com/brainglobe/brainrender/issues/158). 
If you upgrade brainrender now it should be fixed: `pip install brainrender -U`. You might need to downgrade `neurom` with `pip install neurom==1.4.20`

**Comment by SeanNobel** [comment]
It works! Thank you.

However, I ran `brainrender-gui -a allen_mouse_10um`, but all I get is this weird brain-like lines and there's no interface.

Could you help me again?

BTW the example code in the paper worked fine (a pyplot rectangular wave graph that I don't understand appeared before the rendering window though).

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75618251/118482821-3a669480-b750-11eb-9ef4-b101544e7262.png">

**Comment by FedeClaudi** [comment]
Hi,

Do you have either `pyqt5` or `pysid2` installed? The GUI is working fine in my case, do you get any error or warning message?

Which of the paper's examples are you referring to?

**Comment by SeanNobel** [comment]
I checked that `PySide2==5.15.2` was installed, but as PyQt5 was not, I ran `pip install PyQt5`.
Now `PyQt5==5.15.4` is installed, but it didn't solve the problem.

When I came across the error of Qt and PySide earlier, I followed the following instruction (sorry it's in Japanese), so I think I had also installed Qt4 through Homebrew.
http://hiho-developer.hatenablog.com/entry/20160327/1459075409


The example code that worked fine was this:
```python
from brainrender import Scene

scene = Scene(atlas_name='allen_mouse_10um')

scene.add_brain_region("SCm", "ZI")

# scene.add("neuron_mesh.stl", color="tomato")

scene.render()
```

Then I get this window.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/75618251/118489906-52daad00-b758-11eb-8a38-f9ee1a6987fd.png">

After closing that, I get this.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75618251/118490115-8ddce080-b758-11eb-9356-5feb97e96ea5.png">

**Comment by FedeClaudi** [comment]
Is the GUI now working?

And I have no idea why you get a matplotlib plot before the scene comes up, matplotlib is only used in one place in brainrender and only to define some colors. Perhaps you're also running some other code at the same time?

**Comment by SeanNobel** [comment]
GUI is not working yet.
I only can rotate and zoom in/out.

It doesn't seem to be an error, but I get this message when I run `brainrender-gui -a allen_mouse_10um`.
`qt.qpa.fonts: Populating font family aliases took 490 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. `

I'm sure that any other python process is running.

I forgot to mention: if I don't comment out `scene.add()`, I get an error that says neuron_mesh.stl was not found.

**Comment by SeanNobel** [comment]
I noticed that I maybe familiar with the shape of the pyplot graph, so there is a possibility that it's a figure that I generated very long ago.
But even if that's the case, it's too weird that it appears now...

**Comment by SeanNobel** [comment]
I found that `from brainrender import Scene` was generating that pyplot graph. 
I think something weird regarding dependencies is happening in my environment, but please don't worry about it because it's my problem.

**Comment by FedeClaudi** [comment]
okay, yeah probably you have something local to your setup that gets executed by brainrender, weird.

can you send a screenshot of the gui? what exactly is not working?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by SeanNobel** [comment]
Same as before. Now I can't even rotate... and there is no interface.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75618251/118496125-cbdd0300-b75e-11eb-9b31-7f3264e8f3b2.png">

**Comment by FedeClaudi** [comment]
That's very weird indeed. I can't replicate the error so its hard for me to say what might be going wrong. 
Two things you can try:
1. a complete re-install in a new anaconda environment
2. try launching the GUI from a script enabling debugging messages

```python
import brainrender as br

br.set_logging(level='DEBUG')
br.gui.launch()
```
and see if something useful comes up. 

By the way, can you use brainrender outside of the GUI functionality?
